import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Chapters',
      items: [
        'introduction',
        'humanoid-stack',
        'perception-sensing',
        'world-modeling',
        'control-locomotion',
        'manipulation',
        'planning-decision-making',
        'embodied-learning',
        'foundation-models',
        'simulation-sim-to-real',
        'hardware-software-codesign',
        'safety-failure-analysis',
        'future-of-humanoids',
      ],
    },
  ],
};

export default sidebars;
